# Generated by Django 5.0.2 on 2024-03-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAlumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carnet',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
